### ISSUE TITLE
cs cant shoot

### ISSUE THREAD

**Issue by RIckyISdaddy** [SkyHeroes/CSMC#2] opened 2023-01-02 06:52 UTC
unfortunatly i downloaded this plugin and have had lots of issues.
1) there is no way to leave game and even if you swap worlds in sends you back
2) T and ct teams only have 4 guns to choose from and the flashes/grandes ect arent showing up
3) after a few rounds players are no longer able to shoot or damage eachother 
 
 i would love to join your discord or hop in a call to see if you guys already have or cant help me find fixes to this issue

**Comment by barpec12** [comment] 2023-01-02 07:46
Unfortunately we are not working on development of this plugin anymore. At this moment I also don't have access to a pc.
1. This was intended in the version available on Spigot. The plugin required bungeecord setup, where each CSMC arena was on another server. There are though some improvements written by tontito, but I haven't tested them, so this version is available to compile on GitHub, but not on Spigot.
2. Are you using QualityArmory? What version?
3. Hmm, that's interesting, I did not have such problem. What version of spigot do you use?

**Comment by RIckyISdaddy** [comment] 2023-01-03 01:32
im using 1.17.1 
and im useing the newest version of quality armory

**Comment by ricsal1** [comment] 2024-08-09 11:52
> im using 1.17.1 and im useing the newest version of quality armory

Hi,
Have a look at the latest version, we are currently working on make it better and we achieved some goodies, but it is required at least MC 1.20!

https://cdn.modrinth.com/data/kb8KH2vh/versions/zp1JxePs/CSMC.jar

Make sure you use latest QualityArmory

Our discord is https://discord.gg/ubVkqBvyQw

**Comment by ricsal1** [comment] 2024-08-27 20:36
should be working on latest version.
Closing issue, report new one with latest version if you find issues plz

**Closed as completed by ricsal1** 2024-08-27 20:36 UTC
